### ISSUE TITLE
Critical!  Error with signup system due to dependency upgrade.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#1230]
Error with signup:  Swift_MailTransport class not found, and upgrade has broken this, Swiftmail has been converted over to a symfony package and support for swiftmail has been discontinued, so need some kind of better solution.

AC:
- Create a test that goes RED on this situation first!
- consider implementing a mail sendout via AWS SDK
- Connection should be via an external connection, for multi-server compatibility

![image](https://user-images.githubusercontent.com/23353/164144176-df81f46f-fbf3-4a8f-9b4b-bcf223f0c6ec.png)

2022/04/13 10:28:04 [error] 8462#8462: *5097750 FastCGI sent in stderr: "PHP message: Error: Class "Swift_MailTransport" not found in /srv/nw-releases/releases/1648601507/deploy/lib/extensions/Nmail.class.php:80
Stack trace:
#0 /srv/nw-releases/releases/1648601507/deploy/lib/control/SignupController.php(444): Nmail->send()
#1 /srv/nw-releases/releases/1648601507/deploy/lib/control/SignupController.php(103): NinjaWars\core\control\SignupController->sendSignupEmail()
#2 /srv/nw-releases/releases/1648601507/deploy/lib/control/SignupController.php(69): NinjaWars\core\control\SignupController->doWork()
#3 /srv/nw-releases/releases/1648601507/deploy/lib/Router.php(214): NinjaWars\core\control\SignupController->signup()
#4 /srv/nw-releases/releases/1648601507/deploy/lib/Router.php(75): NinjaWars\core\Router::execute()
#5 /srv/nw-releases/releases/1648601507/deploy/www/front-controller.php(32): NinjaWars\core\Router::route()
#6 {main}" while reading response header from upstream, client: 172.31.29.211, server: www.ninjawars.net, request: "POST /signup/signup HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "www.ninjawars.net"

**Comment by tchalvak** [comment]
Alternative, related PR: https://github.com/BitLucid/ninjawars/pull/1198
