### ISSUE TITLE
Invalid emails in swiftmailer throws uncaught exception.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#188]
Whelp, we should be catching this and reporting the error properly to the user.

On Sun, Jan 30, 2011 at 1:59 AM, <noreply@ninjawars.net> wrote:

    Exception message: exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [poopoo@.hotmail.com] does not comply with RFC 2822, 3.6.2.' in /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:309
    Stack trace:
    #0 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(239): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('poopoo@.hotmail...')
    #1 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(97): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
    #2 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(61): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
    #3 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(64): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
    #4 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(77): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)
    #5 /home/ninjawars/game/live/lib/third-party/swift-mailer/lib/classes/Swift/Mime/SimpleMessage.php(301): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)
    #6 /home/ninjawars/game/live/lib/obj/Nmail.class.php(139): Swift_Mime_SimpleMessage->setTo(Array)
    #7 /home/ninjawars/game/live/lib/common/lib_accounts.php(201): Nmail->send()
    #8 /home/ninjawars/game/live/lib/common/lib_accounts.php(216): send_signup_email('12992', 'poopoo@.hotmail...', 'gvfchdsafcdgf', 8259, 'dragon')
    #9 /home/ninjawars/game/live/lib/common/lib_accounts.php(355): create_account_and_ninja('gvfchdsafcdgf', Array)
    #10 /home/ninjawars/game/live/www/signup.php(33): validate_signup('gvfchdsafcdgf', 'poopoo@.hotmail...', 'dragon', NULL, 'ccccccccc')
    #11 {main}

**Comment by tchalvak** [comment]
Wontfix until it comes up again.
