### ISSUE TITLE
Item Use: Use without a target fatal errors.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#518]
AC: 
- the url http://nw.local/item/use/amanita/ should just give a user-facing error.

```
Notice: Undefined variable: targetObj in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 182

Notice: Undefined variable: targetObj in /srv/ninjawars/deploy/lib/control/InventoryController.php on line 261

Fatal error: Uncaught exception 'InvalidArgumentException' with message '$p_target must be a Player object' in /srv/ninjawars/deploy/lib/control/AttackLegal.php:63 Stack trace: #0 /srv/ninjawars/deploy/lib/control/InventoryController.php(261): NinjaWars\core\control\AttackLegal->__construct(Object(Player), NULL, Array) #1 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->useItem() #2 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'use') #3 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /srv/ninjawars/deploy/lib/control/AttackLegal.php on line 63
```

**Comment by tchalvak** [comment]
http://www.ninjawars.net/item/use/amanita/ as well.
