### ISSUE TITLE
Work Page: Player insert breaks on bad input. (on live)

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#520]
Found this in the error log from earlier today:

```
Feb 28 09:53:25 servo-db postgresql-9.3-main.log:  2016-02-28 17:53:32 UTC ERROR:  null value in column "uname" violates not-null constraint
Feb 28 09:53:25 servo-db postgresql-9.3-main.log:  2016-02-28 17:53:32 UTC DETAIL:  Failing row contains (169880, null, null, null, null, 0, null, null, 0, null, null, , null, null, 0, null, , null, null, 15, null, null, null, null, null, null, null, null, 0, 0, null, null, null, null, null).
Feb 28 09:53:25 servo-db postgresql-9.3-main.log:  2016-02-28 17:53:32 UTC STATEMENT:  INSERT INTO players (player_id, uname, health, strength, speed, stamina, ki, karma, gold, messages, kills, turns, active, _class_id, level, status, days, bounty, created_date, last_started_attack, energy, avatar_type, verification_number, description, beliefs, goals, instincts, traits) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
```
php script source unknown, but probably signup.
Not good.

**Comment by tchalvak** [comment]
Possibly a duplicate of: https://github.com/BitLucid/ninjawars/issues/592

**Comment by tchalvak** [comment]
Yay!  Now that the server properly sends back 500 errors, this is being logged correctly, for some reason:

2016/03/24 22:24:33 [error] 32692#0: *883906 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "uname" violates not-null constraint
DETAIL:  Failing row contains (169931, null, null, 150, 5, 100, , 0, 180, null, null, , 1, 0, 0, 0, , 0, null, 7, 2016-01-01 00:00:00+00, 0, 1, null, 0, 5, 5, 0, 0, 0, , , , , ).' in /srv/ninjawars/deploy/lib/data/DataAccessObject.php:136
Stack trace:
#0 /srv/ninjawars/deploy/lib/data/DataAccessObject.php(136): PDOStatement->execute()
#1 /srv/ninjawars/deploy/lib/data/DataAccessObject.php(33): NinjaWars\core\data\DataAccessObject->_insert(Object(NinjaWars\core\data\PlayerVO))
#2 /srv/ninjawars/deploy/lib/data/Player.php(638): NinjaWars\core\data\DataAccessObject->save(Object(NinjaWars\core\data\PlayerVO))
#3 /srv/ninjawars/deploy/lib/control/WorkController.php(39): NinjaWars\core\data\Player->save()
#4 /srv/ninjawars/deploy/lib/Router.php(224): NinjaWars\core\control\WorkController->requestWork()
#5 /srv/ninjawars/deploy/lib" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /work/request_work HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net"
2016/03/24 22:25:33 [error] 32689#0: *883980 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "uname" violates not-null constraint
DETAIL:  Failing row contains (169932, null, null, 150, 5, 100, , 0, 180, null, null, , 1, 0, 0, 0, , 0, null, 8, 2016-01-01 00:00:00+00, 0, 1, null, 0, 5, 5, 0, 0, 0, , , , , ).' in /srv/ninjawars/deploy/lib/data/DataAccessObject.php:136
Stack trace:
#0 /srv/ninjawars/deploy/lib/data/DataAccessObject.php(136): PDOStatement->execute()
#1 /srv/ninjawars/deploy/lib/data/DataAccessObject.php(33): NinjaWars\core\data\DataAccessObject->_insert(Object(NinjaWars\core\data\PlayerVO))
#2 /srv/ninjawars/deploy/lib/data/Player.php(638): NinjaWars\core\data\DataAccessObject->save(Object(NinjaWars\core\data\PlayerVO))
#3 /srv/ninjawars/deploy/lib/control/WorkController.php(39): NinjaWars\core\data\Player->save()
#4 /srv/ninjawars/deploy/lib/Router.php(224): NinjaWars\core\control\WorkController->requestWork()
#5 /srv/ninjawars/deploy/lib" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /work/request_work HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net"

So it looks like this is a work_request being made by a logged-out user (probably being spidered by googlebot or something).

**Comment by tchalvak** [comment]
Definitely duplicated, yay:
http://www.ninjawars.net/work/request_work (while logged out)
