### ISSUE TITLE
Amanita: Error, when you have zero turns, and try to use any item, e.g. an amanita mushroom, it errors out. (on live)

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#593]
Amanita: Error with trying to set turns to -1 via subtractTurns(1), in inventory controller. (on live)

Mar 16 11:37:50 megaman error.log:  2016/03/14 21:17:23 [error] 13643#0: *272673 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Turns cannot be made negative.' in /srv/ninjawars/deploy/lib/control/Player.class.php:431
Mar 16 11:37:50 megaman error.log:  Stack trace:
Mar 16 11:37:50 megaman error.log:  #0 /srv/ninjawars/deploy/lib/control/Player.class.php(443): Player->set_turns(-1)
Mar 16 11:37:50 megaman error.log:  #1 /srv/ninjawars/deploy/lib/control/Player.class.php(460): Player->changeTurns(-1)
Mar 16 11:37:50 megaman error.log:  #2 /srv/ninjawars/deploy/lib/control/InventoryController.php(470): Player->subtractTurns(1)
Mar 16 11:37:50 megaman error.log:  #3 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->useItem()
Mar 16 11:37:50 megaman error.log:  #4 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'use')
Mar 16 11:37:50 megaman error.log:  #5 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request))
Mar 16 11:37:50 megaman error.log:  #6 {main}
Mar 16 11:37:50 megaman error.log:    thrown in /srv/ninjawars/deploy/lib/control/Player.class.php on line 431" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /item/use/5/92283 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/player?target_id=92283"
Mar 16 11:37:50 megaman error.log:  2016/03/15 04:24:37 [error] 13642#0: *301174 FastCGI sent in stderr: "PHP message: PHP Warning:  Division by zero in /srv/ninjawars/deploy/lib/control/Player.class.php on line 491" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /api.php?type=index&jsoncallback=jQuery21103620924430433661_1458033815888&_=1458033815890 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/"

**Comment by tchalvak** [comment]
2016/03/18 01:36:51 [error] 13645#0: *472812 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Turns cannot be made negative.' in /srv/ninjawars/deploy/lib/control/Player.class.php:431
Stack trace:
#0 /srv/ninjawars/deploy/lib/control/Player.class.php(443): Player->set_turns(-1)
#1 /srv/ninjawars/deploy/lib/control/Player.class.php(460): Player->changeTurns(-1)
#2 /srv/ninjawars/deploy/lib/control/InventoryController.php(470): Player->subtractTurns(1)
#3 /srv/ninjawars/deploy/lib/control/InventoryController.php(77): NinjaWars\core\control\InventoryController->useItem(false, true)
#4 /srv/ninjawars/deploy/lib/Router.php(223): NinjaWars\core\control\InventoryController->self_use()
#5 /srv/ninjawars/deploy/lib/Router.php(66): NinjaWars\core\Router::execute('inventory', 'self_use')
#6 /srv/ninjawars/deploy/www/front-controller.php(9): NinjaWars\core\Router::route(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
  thrown in /srv/ninjawars/deploy/lib/control/Player.class.php on line 431" while reading response header from upstream, client: 10.189.245.10, server: www.ninjawars.net, request: "GET /item/self_use/3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.ninjawars.net", referrer: "http://www.ninjawars.net/inventory"
